local _, ns = ...

if type(GetLocale) ~= "function" or GetLocale() ~= "deDE" then
    return
end

local L = ns.L
L.CONTACTS_TITLE = "Kontakte"
L.TAB_GENERAL = "ALLGEMEIN"
L.TAB_GUILD = "GUILD"
L.TAB_FAVORITES = "FAVORITEN"
L.SEARCH_PLACEHOLDER = "Suchen"
L.SEARCH_ONLINE = "Online suchen"
L.SEARCHING = "Suche..."
L.SEARCHING_ONLINE = "Online-Suche läuft..."
L.WHO_UNAVAILABLE = "Die Online-Suche ist in diesem Client nicht verfügbar."
L.WHO_COOLDOWN = "Die Online-Suche hat vorübergehend Abklingzeit."
L.WHO_START_FAILED = "Die Online-Suche konnte nicht gestartet werden."
L.WHO_TIMEOUT = "Zeitüberschreitung bei der Online-Suche."
L.WHO_PROCESS_FAILED = "Die Online-Ergebnisse konnten nicht verarbeitet werden."
L.WHO_NO_RESULTS = "Keine Online-Ergebnisse gefunden."
L.WHO_RESULTS_PARTIAL = "Online-Suche: %d von %d Ergebnissen angezeigt."
L.WHO_RESULTS = "Online-Suche: %d Ergebnis(se) gefunden."
L.NO_MATCHES = "Keine passenden Charaktere."
L.NOT_IN_GUILD = "Dieser Charakter ist in keiner Gilde."
L.GUILD_LOADING = "Gildenmitglieder werden geladen..."
L.GUILD_UNAVAILABLE = "Die Gildenliste ist in diesem Client nicht verfügbar."
L.NO_GUILD_MEMBERS = "Keine Gildenmitglieder verfügbar."
L.NO_FAVORITES = "Noch keine favorisierten Charaktere."
L.NO_KNOWN_CHARACTERS = "Noch keine bekannten Charaktere."
L.SET_MAIL_RECIPIENT = "Als Briefempfänger festlegen"
L.ADD_FAVORITE = "Favorit hinzufügen"
L.REMOVE_FAVORITE = "Favorit entfernen"
L.ONLINE = "Online"
L.OFFLINE = "Offline"
L.LOADING_PLAYERS = "Charakterinformationen werden geladen..."
L.READY_SUMMARY = "Bereit: %s · %s · %d Favoriten."
L.CONTACTS_COUNT = "%d Kontakte"
L.GUILD_COUNT = "%d Gildenmitglieder"
L.NO_GUILD = "keine Gilde"
L.GUILD_PENDING = "Gilde ausstehend"
L.PLAYER_UNAVAILABLE = "Spieler nicht verfügbar"
L.FRIENDS_UNAVAILABLE = "Freunde nicht verfügbar"
L.CMD_SEARCH_RESULTS = "%d Ergebnis(se) für %q:"
L.CMD_SEARCH_RESULT = "%d. %s (Wertung %d)"
L.CMD_STATUS = "%s; Schema %s; Brief-Autovervollständigung %s; Flüster-Autovervollständigung %s; Kontakte %s."
L.STATUS_INSTALLED = "installiert"
L.STATUS_WAITING_MAIL = "wartet auf Blizzard_MailFrame"
L.STATUS_WAITING_CHAT = "wartet auf Chat-Eingabefelder"
L.CMD_HELP = "Verwende /fefs search <Name>, /fefs debug oder /fefs debug perf."
L.PERF_UNAVAILABLE = "Leistungsmessung nicht verfügbar: debugprofilestop() wurde nicht gefunden."
L.PERF_HEADER = "Leistungswerte (Millisekunden):"
L.PERF_GUILD = "Gilde: Ereignisse=%d, Ausführungen=%d, zusammengefasst=%d, letzte=%.2f, Maximum=%.2f, verarbeitet=%d, geändert=%d"
L.PERF_SEARCH_REFRESH = "Search.Refresh: Ausführungen=%d, letzte=%.2f, Maximum=%.2f, indexiert=%d"
L.PERF_SEARCH_REFRESH_DETAIL = "  Datensätze=%.2f, Klassen=%.2f, Aufbau=%.2f, normalisiert=%d, Cache-Treffer=%d"
L.PERF_SEARCH_FIND = "Search.Find: Ausführungen=%d, letzte=%.2f, Maximum=%.2f, geprüft=%d, Treffer=%d"
L.PERF_SEARCH_FILTER = "Search.Filter: Ausführungen=%d, letzte=%.2f, Maximum=%.2f, geprüft=%d, Treffer=%d"
L.PERF_CONTACTS_REFRESH = "MailContacts.Refresh: Aufrufe=%d, letzte=%.2f, Maximum=%.2f, logisch=%d, gerendert=%d, übersprungen=%d"
L.PERF_CONTACTS_REASONS = "  Suche=%d, Scroll=%d, Invalidierung=%d, Tab=%d, Anzeige=%d, andere=%d"
