local _, ns = ...

if type(GetLocale) ~= "function" or GetLocale() ~= "deDE" then
    return
end

local L = ns.L
L.CONTACTS_TITLE = "Kontakte"
L.TAB_GENERAL = "Allgemein"
L.TAB_GUILD = "Gilde"
L.TAB_FAVORITES = "Favoriten"
L.SEARCH_PLACEHOLDER = "Spieler suchen..."
L.SEARCH_ONLINE = "Online suchen"
L.SEARCHING = "Suche..."
L.SEARCHING_ONLINE = "Online-Suche läuft..."
L.WHO_UNAVAILABLE = "Die Online-Suche ist in diesem Client nicht verfügbar."
L.WHO_COOLDOWN = "Die Online-Suche hat vorübergehend Abklingzeit."
L.WHO_START_FAILED = "Die Online-Suche konnte nicht gestartet werden."
L.WHO_TIMEOUT = "Zeitüberschreitung bei der Online-Suche."
L.WHO_PROCESS_FAILED = "Die Online-Ergebnisse konnten nicht verarbeitet werden."
L.WHO_NO_RESULTS = "Keine Online-Ergebnisse gefunden."
L.WHO_RESULTS_PARTIAL = "Online-Suche: %d von %d Ergebnissen angezeigt."
L.WHO_RESULTS = "Online-Suche: %d Ergebnis(se) gefunden."
L.NO_MATCHES = "Keine passenden Charaktere."
L.NOT_IN_GUILD = "Dieser Charakter ist in keiner Gilde."
L.GUILD_LOADING = "Gildenmitglieder werden geladen..."
L.GUILD_UNAVAILABLE = "Die Gildenliste ist in diesem Client nicht verfügbar."
L.NO_GUILD_MEMBERS = "Keine Gildenmitglieder verfügbar."
L.NO_FAVORITES = "Noch keine favorisierten Charaktere."
L.NO_KNOWN_CHARACTERS = "Noch keine bekannten Charaktere."
L.SET_MAIL_RECIPIENT = "Brief schreiben"
L.ADD_FAVORITE = "Favorit hinzufügen"
L.REMOVE_FAVORITE = "Favorit entfernen"
L.HIDE_CONTACTS = "Kontakte ausblenden"
L.SHOW_CONTACTS = "Kontakte anzeigen"
L.ONLINE = "Online"
L.OFFLINE = "Offline"
L.LOADING_PLAYERS = "Charakterinformationen werden geladen..."
L.READY_SUMMARY = "Bereit: %s · %s · %d Favoriten."
L.CONTACTS_COUNT = "%d Kontakte"
L.GUILD_COUNT = "%d Gildenmitglieder"
L.NO_GUILD = "keine Gilde"
L.GUILD_PENDING = "Gilde ausstehend"
L.PLAYER_UNAVAILABLE = "Spieler nicht verfügbar"
L.FRIENDS_UNAVAILABLE = "Freunde nicht verfügbar"
L.CMD_SEARCH_RESULTS = "%d Ergebnis(se) für %q:"
L.CMD_SEARCH_RESULT = "%d. %s (Wertung %d)"
L.CMD_STATUS = "%s; Schema %s; Brief-Autovervollständigung %s; Flüster-Autovervollständigung %s; Kontakte %s."
L.STATUS_INSTALLED = "installiert"
L.STATUS_WAITING_MAIL = "wartet auf Blizzard_MailFrame"
L.STATUS_WAITING_CHAT = "wartet auf Chat-Eingabefelder"
L.CMD_HELP = "Verwende /fefs search <Name>, /fefs debug oder /fefs debug perf [on|off|reset]."
L.PERF_UNAVAILABLE = "Leistungsmessung nicht verfügbar: debugprofilestop() wurde nicht gefunden."
L.PERF_HEADER = "Leistungsdiagnose: %s · Langsam-Schwelle %.0f ms"
L.PERF_ON = "AKTIV"
L.PERF_OFF = "INAKTIV"
L.PERF_ENABLED = "Leistungsdiagnose aktiviert."
L.PERF_DISABLED = "Leistungsdiagnose deaktiviert."
L.PERF_RESET_DONE = "Leistungsdiagnose zurückgesetzt."
L.PERF_COMMAND_HELP = "Verwende /fefs debug perf [on|off|reset]."
L.PERF_GUILD_EVENTS = "Gildenereignisse: %d empfangen · %d zusammengefasst"
L.PERF_OPERATION = "%s: Aufrufe=%d letzte=%.2f ms Maximum=%.2f ms gesamt=%.2f ms"
L.PERF_SLOW_HEADER = "Letzte langsame Aufrufe: %d/%d"
L.PERF_SLOW_ENTRY = "LANGSAM #%d t=%.1f %s %.2f ms %s"
