local _, ns = ...

ns.L = {
    CONTACTS_TITLE = "Contacts",
    TAB_GENERAL = "GENERAL",
    TAB_GUILD = "GUILD",
    TAB_FAVORITES = "FAVORITES",
    SEARCH_PLACEHOLDER = "Search",
    SEARCH_ONLINE = "Search Online",
    SEARCHING = "Searching...",
    SEARCHING_ONLINE = "Searching online...",
    WHO_UNAVAILABLE = "Online search is unavailable in this client.",
    WHO_COOLDOWN = "Online search is temporarily on cooldown.",
    WHO_START_FAILED = "Online search could not be started.",
    WHO_TIMEOUT = "Online search timed out.",
    WHO_PROCESS_FAILED = "Online results could not be processed.",
    WHO_NO_RESULTS = "No online results found.",
    WHO_RESULTS_PARTIAL = "Online search: %d of %d results shown.",
    WHO_RESULTS = "Online search: %d result(s) found.",
    NO_MATCHES = "No matching characters.",
    NOT_IN_GUILD = "This character is not in a guild.",
    GUILD_LOADING = "Loading guild roster...",
    GUILD_UNAVAILABLE = "Guild roster is unavailable in this client.",
    NO_GUILD_MEMBERS = "No guild members available.",
    NO_FAVORITES = "No favorite characters yet.",
    NO_KNOWN_CHARACTERS = "No known characters yet.",
    SET_MAIL_RECIPIENT = "Set mail recipient",
    ADD_FAVORITE = "Add favorite",
    REMOVE_FAVORITE = "Remove favorite",
    ONLINE = "Online",
    OFFLINE = "Offline",
    LOADING_PLAYERS = "Loading character information...",
    READY_SUMMARY = "Ready: %s · %s · %d favorites.",
    CONTACTS_COUNT = "%d contacts",
    GUILD_COUNT = "%d guild members",
    NO_GUILD = "no guild",
    GUILD_PENDING = "guild pending",
    PLAYER_UNAVAILABLE = "player unavailable",
    FRIENDS_UNAVAILABLE = "friends unavailable",
    CMD_SEARCH_RESULTS = "%d result(s) for %q:",
    CMD_SEARCH_RESULT = "%d. %s (score %d)",
    CMD_STATUS = "%s; schema %s; mail autocomplete %s; whisper autocomplete %s; contacts panel %s.",
    STATUS_INSTALLED = "installed",
    STATUS_WAITING_MAIL = "waiting for Blizzard_MailFrame",
    STATUS_WAITING_CHAT = "waiting for chat edit boxes",
    CMD_HELP = "Use /fefs search <name>, /fefs debug, or /fefs debug perf.",
    DEBUG_SOURCES = "debug: player=%s, friends=%s (%d), guild=%s (%d), group=%s",
    DEBUG_WHO = "debug: whoAvailable=%s, whoPending=%s, lastWhoQuery=%q, cooldownRemaining=%.1f",
    DEBUG_WHO_ERROR = "debug: last WHO error=%s",
    PERF_UNAVAILABLE = "Performance timing is unavailable: debugprofilestop() was not found.",
    PERF_HEADER = "Performance metrics (milliseconds):",
    PERF_GUILD = "guild: events=%d, runs=%d, coalesced=%d, last=%.2f, max=%.2f, processed=%d, modified=%d",
    PERF_SEARCH_REFRESH = "Search.Refresh: runs=%d, last=%.2f, max=%.2f, indexed=%d",
    PERF_SEARCH_REFRESH_DETAIL = "  records=%.2f, classes=%.2f, build=%.2f, normalized=%d, cache hits=%d",
    PERF_SEARCH_FIND = "Search.Find: runs=%d, last=%.2f, max=%.2f, scanned=%d, matched=%d",
    PERF_SEARCH_FILTER = "Search.Filter: runs=%d, last=%.2f, max=%.2f, scanned=%d, matched=%d",
    PERF_CONTACTS_REFRESH = "MailContacts.Refresh: calls=%d, last=%.2f, max=%.2f, logical=%d, rendered=%d, skipped=%d",
    PERF_CONTACTS_REASONS = "  search=%d, scroll=%d, invalidation=%d, tab=%d, show=%d, other=%d",
}
