local _, ns = ...

local locale = type(GetLocale) == "function" and GetLocale() or "enUS"
if locale ~= "esES" and locale ~= "esMX" then
    return
end

local L = ns.L
L.CONTACTS_TITLE = "Agenda"
L.TAB_GENERAL = "GENERAL"
L.TAB_GUILD = "HERMANDAD"
L.TAB_FAVORITES = "FAVORITOS"
L.SEARCH_PLACEHOLDER = "Buscar"
L.SEARCH_ONLINE = "Buscar en línea"
L.SEARCHING = "Buscando..."
L.SEARCHING_ONLINE = "Buscando en línea..."
L.WHO_UNAVAILABLE = "La búsqueda en línea no está disponible en este cliente."
L.WHO_COOLDOWN = "La búsqueda en línea está temporalmente en reutilización."
L.WHO_START_FAILED = "No se pudo iniciar la búsqueda en línea."
L.WHO_TIMEOUT = "La búsqueda en línea agotó el tiempo de espera."
L.WHO_PROCESS_FAILED = "No se pudieron procesar los resultados en línea."
L.WHO_NO_RESULTS = "No se encontraron resultados en línea."
L.WHO_RESULTS_PARTIAL = "Búsqueda en línea: se muestran %d de %d resultados."
L.WHO_RESULTS = "Búsqueda en línea: %d resultado(s)."
L.NO_MATCHES = "No hay personajes coincidentes."
L.NOT_IN_GUILD = "Este personaje no pertenece a una hermandad."
L.GUILD_LOADING = "Cargando miembros de la hermandad..."
L.GUILD_UNAVAILABLE = "La lista de la hermandad no está disponible en este cliente."
L.NO_GUILD_MEMBERS = "No hay miembros de hermandad disponibles."
L.NO_FAVORITES = "Todavía no hay personajes favoritos."
L.NO_KNOWN_CHARACTERS = "Todavía no hay personajes conocidos."
L.SET_MAIL_RECIPIENT = "Usar como destinatario del correo"
L.ADD_FAVORITE = "Añadir a favoritos"
L.REMOVE_FAVORITE = "Quitar de favoritos"
L.ONLINE = "Conectado"
L.OFFLINE = "Desconectado"
L.LOADING_PLAYERS = "Cargando información de personajes..."
L.READY_SUMMARY = "Listo: %s · %s · %d favoritos."
L.CONTACTS_COUNT = "%d contactos"
L.GUILD_COUNT = "%d miembros de hermandad"
L.NO_GUILD = "sin hermandad"
L.GUILD_PENDING = "hermandad pendiente"
L.PLAYER_UNAVAILABLE = "jugador no disponible"
L.FRIENDS_UNAVAILABLE = "amigos no disponibles"
L.CMD_SEARCH_RESULTS = "%d resultado(s) para %q:"
L.CMD_SEARCH_RESULT = "%d. %s (puntuación %d)"
L.CMD_STATUS = "%s; esquema %s; autocomplete de correo %s; autocomplete de susurro %s; agenda %s."
L.STATUS_INSTALLED = "instalado"
L.STATUS_WAITING_MAIL = "esperando Blizzard_MailFrame"
L.STATUS_WAITING_CHAT = "esperando campos de chat"
L.CMD_HELP = "Usa /fefs search <nombre>, /fefs debug o /fefs debug perf."
L.DEBUG_SOURCES = "debug: jugador=%s, amigos=%s (%d), hermandad=%s (%d), grupo=%s"
L.DEBUG_WHO_ERROR = "debug: último error de WHO=%s"
L.PERF_UNAVAILABLE = "Las métricas de rendimiento no están disponibles: no se encontró debugprofilestop()."
L.PERF_HEADER = "Métricas de rendimiento (milisegundos):"
L.PERF_GUILD = "hermandad: eventos=%d, ejecuciones=%d, agrupados=%d, última=%.2f, máxima=%.2f, procesados=%d, modificados=%d"
L.PERF_SEARCH_REFRESH = "Search.Refresh: ejecuciones=%d, última=%.2f, máxima=%.2f, indexados=%d"
L.PERF_SEARCH_FIND = "Search.Find: ejecuciones=%d, última=%.2f, máxima=%.2f, recorridos=%d, coincidencias=%d"
L.PERF_SEARCH_FILTER = "Search.Filter: ejecuciones=%d, última=%.2f, máxima=%.2f, recorridos=%d, coincidencias=%d"
L.PERF_CONTACTS_REFRESH = "MailContacts.Refresh: ejecuciones=%d, última=%.2f, máxima=%.2f"
