local _, ns = ...

if type(GetLocale) ~= "function" or GetLocale() ~= "frFR" then
    return
end

local L = ns.L
L.CONTACTS_TITLE = "Contacts"
L.TAB_GENERAL = "GÉNÉRAL"
L.TAB_GUILD = "GUILD"
L.TAB_FAVORITES = "FAVORIS"
L.SEARCH_PLACEHOLDER = "Rechercher"
L.SEARCH_ONLINE = "Rechercher en ligne"
L.SEARCHING = "Recherche..."
L.SEARCHING_ONLINE = "Recherche en ligne..."
L.WHO_UNAVAILABLE = "La recherche en ligne n’est pas disponible dans ce client."
L.WHO_COOLDOWN = "La recherche en ligne est temporairement en recharge."
L.WHO_START_FAILED = "Impossible de lancer la recherche en ligne."
L.WHO_TIMEOUT = "La recherche en ligne a expiré."
L.WHO_PROCESS_FAILED = "Impossible de traiter les résultats en ligne."
L.WHO_NO_RESULTS = "Aucun résultat en ligne."
L.WHO_RESULTS_PARTIAL = "Recherche en ligne : %d résultats affichés sur %d."
L.WHO_RESULTS = "Recherche en ligne : %d résultat(s)."
L.NO_MATCHES = "Aucun personnage correspondant."
L.NOT_IN_GUILD = "Ce personnage n’appartient à aucune guilde."
L.GUILD_LOADING = "Chargement de la guilde..."
L.GUILD_UNAVAILABLE = "La liste de guilde n’est pas disponible dans ce client."
L.NO_GUILD_MEMBERS = "Aucun membre de guilde disponible."
L.NO_FAVORITES = "Aucun personnage favori pour le moment."
L.NO_KNOWN_CHARACTERS = "Aucun personnage connu pour le moment."
L.SET_MAIL_RECIPIENT = "Définir comme destinataire"
L.ADD_FAVORITE = "Ajouter aux favoris"
L.REMOVE_FAVORITE = "Retirer des favoris"
L.ONLINE = "En ligne"
L.OFFLINE = "Hors ligne"
L.LOADING_PLAYERS = "Chargement des informations des personnages..."
L.READY_SUMMARY = "Prêt : %s · %s · %d favoris."
L.CONTACTS_COUNT = "%d contacts"
L.GUILD_COUNT = "%d membres de guilde"
L.NO_GUILD = "sans guilde"
L.GUILD_PENDING = "guilde en attente"
L.PLAYER_UNAVAILABLE = "joueur indisponible"
L.FRIENDS_UNAVAILABLE = "amis indisponibles"
L.CMD_SEARCH_RESULTS = "%d résultat(s) pour %q :"
L.CMD_SEARCH_RESULT = "%d. %s (score %d)"
L.CMD_STATUS = "%s ; schéma %s ; saisie auto. courrier %s ; saisie auto. chuchotement %s ; contacts %s."
L.STATUS_INSTALLED = "installée"
L.STATUS_WAITING_MAIL = "en attente de Blizzard_MailFrame"
L.STATUS_WAITING_CHAT = "en attente des champs de discussion"
L.CMD_HELP = "Utilisez /fefs search <nom>, /fefs debug ou /fefs debug perf."
L.PERF_UNAVAILABLE = "Mesure des performances indisponible : debugprofilestop() est introuvable."
L.PERF_HEADER = "Mesures de performances (millisecondes) :"
L.PERF_GUILD = "guilde : événements=%d, exécutions=%d, regroupés=%d, dernière=%.2f, maximum=%.2f, traités=%d, modifiés=%d"
L.PERF_SEARCH_REFRESH = "Search.Refresh : exécutions=%d, dernière=%.2f, maximum=%.2f, indexés=%d"
L.PERF_SEARCH_REFRESH_DETAIL = "  enregistrements=%.2f, classes=%.2f, construction=%.2f, normalisés=%d, accès cache=%d"
L.PERF_SEARCH_FIND = "Search.Find : exécutions=%d, dernière=%.2f, maximum=%.2f, parcourus=%d, correspondances=%d"
L.PERF_SEARCH_FILTER = "Search.Filter : exécutions=%d, dernière=%.2f, maximum=%.2f, parcourus=%d, correspondances=%d"
L.PERF_CONTACTS_REFRESH = "MailContacts.Refresh : appels=%d, dernière=%.2f, maximum=%.2f, logiques=%d, rendus=%d, ignorés=%d"
L.PERF_CONTACTS_REASONS = "  recherche=%d, défilement=%d, invalidation=%d, onglet=%d, affichage=%d, autres=%d"
