local _, ns = ...

if type(GetLocale) ~= "function" or GetLocale() ~= "frFR" then
    return
end

local L = ns.L
L.CONTACTS_TITLE = "Contacts"
L.TAB_GENERAL = "Général"
L.TAB_GUILD = "Guilde"
L.TAB_FAVORITES = "Favoris"
L.SEARCH_PLACEHOLDER = "Rechercher un joueur..."
L.SEARCH_ONLINE = "Rechercher en ligne"
L.SEARCHING = "Recherche..."
L.SEARCHING_ONLINE = "Recherche en ligne..."
L.WHO_UNAVAILABLE = "La recherche en ligne n’est pas disponible dans ce client."
L.WHO_COOLDOWN = "La recherche en ligne est temporairement en recharge."
L.WHO_START_FAILED = "Impossible de lancer la recherche en ligne."
L.WHO_TIMEOUT = "La recherche en ligne a expiré."
L.WHO_PROCESS_FAILED = "Impossible de traiter les résultats en ligne."
L.WHO_NO_RESULTS = "Aucun résultat en ligne."
L.WHO_RESULTS_PARTIAL = "Recherche en ligne : %d résultats affichés sur %d."
L.WHO_RESULTS = "Recherche en ligne : %d résultat(s)."
L.NO_MATCHES = "Aucun personnage correspondant."
L.NOT_IN_GUILD = "Ce personnage n’appartient à aucune guilde."
L.GUILD_LOADING = "Chargement de la guilde..."
L.GUILD_UNAVAILABLE = "La liste de guilde n’est pas disponible dans ce client."
L.NO_GUILD_MEMBERS = "Aucun membre de guilde disponible."
L.NO_FAVORITES = "Aucun personnage favori pour le moment."
L.NO_KNOWN_CHARACTERS = "Aucun personnage connu pour le moment."
L.SET_MAIL_RECIPIENT = "Écrire un courrier"
L.ADD_FAVORITE = "Ajouter aux favoris"
L.REMOVE_FAVORITE = "Retirer des favoris"
L.HIDE_CONTACTS = "Masquer les contacts"
L.SHOW_CONTACTS = "Afficher les contacts"
L.ONLINE = "En ligne"
L.OFFLINE = "Hors ligne"
L.LOADING_PLAYERS = "Chargement des informations des personnages..."
L.READY_SUMMARY = "Prêt : %s · %s · %d favoris."
L.CONTACTS_COUNT = "%d contacts"
L.GUILD_COUNT = "%d membres de guilde"
L.NO_GUILD = "sans guilde"
L.GUILD_PENDING = "guilde en attente"
L.PLAYER_UNAVAILABLE = "joueur indisponible"
L.FRIENDS_UNAVAILABLE = "amis indisponibles"
L.CMD_SEARCH_RESULTS = "%d résultat(s) pour %q :"
L.CMD_SEARCH_RESULT = "%d. %s (score %d)"
L.CMD_STATUS = "%s ; schéma %s ; saisie auto. courrier %s ; saisie auto. chuchotement %s ; contacts %s."
L.STATUS_INSTALLED = "installée"
L.STATUS_WAITING_MAIL = "en attente de Blizzard_MailFrame"
L.STATUS_WAITING_CHAT = "en attente des champs de discussion"
L.CMD_HELP = "Utilisez /fefs search <nom>, /fefs debug ou /fefs debug perf [on|off|reset]."
L.PERF_UNAVAILABLE = "Mesure des performances indisponible : debugprofilestop() est introuvable."
L.PERF_HEADER = "Diagnostic des performances : %s · seuil lent %.0f ms"
L.PERF_ON = "ACTIF"
L.PERF_OFF = "INACTIF"
L.PERF_ENABLED = "Diagnostic des performances activé."
L.PERF_DISABLED = "Diagnostic des performances désactivé."
L.PERF_RESET_DONE = "Diagnostic des performances réinitialisé."
L.PERF_COMMAND_HELP = "Utilisez /fefs debug perf [on|off|reset]."
L.PERF_GUILD_EVENTS = "Événements de guilde : %d reçus · %d regroupés"
L.PERF_OPERATION = "%s : appels=%d dernier=%.2f ms maximum=%.2f ms total=%.2f ms"
L.PERF_SLOW_HEADER = "Appels lents récents : %d/%d"
L.PERF_SLOW_ENTRY = "LENT #%d t=%.1f %s %.2f ms %s"
